name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod download

    - name: Build all platforms
      run: |
        mkdir -p dist

        # Build for each platform
        platforms="linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"

        for platform in $platforms; do
          GOOS=$(echo $platform | cut -d'/' -f1)
          GOARCH=$(echo $platform | cut -d'/' -f2)

          EXT=""
          if [ "$GOOS" = "windows" ]; then
            EXT=".exe"
          fi

          BINARY_NAME="ministo-$GOOS-$GOARCH$EXT"
          echo "Building $BINARY_NAME..."

          GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-s -w" -o "dist/$BINARY_NAME" ./cmd/ministo

          # Create archive
          cd dist
          if [ "$GOOS" = "windows" ]; then
            zip "../ministo-$GOOS-$GOARCH.zip" "$BINARY_NAME"
          else
            tar -czf "../ministo-$GOOS-$GOARCH.tar.gz" "$BINARY_NAME"
          fi
          cd ..
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          *.zip
          *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}